### PR TITLE
Enable Static Build on Alpine

### PR DESCRIPTION
**Pull request by william00179**
Update the Readme to include the deps required to build audiowaveform as well as some extra deps required to build a static binary on Alpine. The Alpine distribution of FLAC doesn't contain a portable lib so I have added a guide as to how to compile this.

I'll preface this with I'm not great with CMake and the flags I have added allow it to build and run successfully on Alpine but may have other effects on other distros that I'm unable to test. 

Relates to #76

### CODE REVIEW

**Comment by chrisn** [comment]
I'm just trying a static build using Alpine 3.11.3, but get an error finding libpng:

```
# cmake -D BUILD_STATIC=1 ..
-- Build type not specified: default is Release
-- CMAKE_VERSION=3.15.5
-- Build type: Release
-- CMAKE_MODULE_PATH='/root/audiowaveform/cmake/modules'
-- Building version 1.4.1
-- Static build
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137
  (message):
  Could NOT find PNG (missing: PNG_PNG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378
    (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindPNG.cmake:146 (find_package_handle_standard_args)
  cmake/modules/FindLibGD.cmake:39 (find_package)
  CMakeLists.txt:84 (find_package)
```

**Comment by william00179** [comment]
Have you included the [additional deps required for a static build](https://github.com/bbc/audiowaveform/pull/106/files#diff-04c6e90faac2675aa89e2176d2eec7d8R94)?

Are you using docker to run the build? If so does the following Dockerfile work for you?

```
FROM alpine:3.11

RUN apk add --no-cache git make cmake gcc g++ libmad-dev zlib-dev zlib-static libpng-static libpng-dev libgd \
                       libid3tag-dev libsndfile-dev gd-dev boost-static boost-dev build-base autoconf automake gettext libtool \
    && cp /lib/libz* /usr/lib \
    && wget https://github.com/xiph/flac/archive/1.3.3.tar.gz \
    && tar xzf 1.3.3.tar.gz \
    && ls \
    && cd flac-1.3.3 \
    && ./autogen.sh \
    && ./configure --enable-shared=no \
    && make -j${nproc}\
    && make install \
    && cd ../ \
    && git clone https://github.com/william00179/audiowaveform.git \
    && cd audiowaveform \
    && wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz \
    && tar xzf release-1.10.0.tar.gz \
    && ln -s googletest-release-1.10.0/googletest googletest \
    && ln -s googletest-release-1.10.0/googlemock googlemock \
    && mkdir build \
    && cd build \
    && cmake -D BUILD_STATIC=1 .. \
    && make -j${nproc}\
    && cp audiowaveform* /bin \
    && cd \
    && rm -rf /audiowaveform
```

**Comment by chrisn** [comment]
I'm not using Docker, I installed Alpine in a virtual machine.

**Comment by chrisn** [comment]
It turns out I'd missed adding `libpng-dev`. The other packages I needed to add were `autoconf`, `automake`, `libtool`, and `gettext`. I'll merge and document these in another commit.

**Comment by chrisn** [comment]
Thank you for your contribution, @william00179 !

**Comment by shealan** [comment]
Is there a way of installing on an Alpine box without building from source? I can't for the life of me get it running on the Alpine box our application runs on. Any way to just pull in the binary?

**Comment by william00179** [comment]
@shealan there is no audiowaveform package published in the Alpine package registry and I'm not aware of a binary you can download. 

If you could share some more information about the build steps you have taken as well as the version of Alpine you're running I'd be happy to take a look. Are you trying to build this into a Docker container? If so I published a base image a while back you can use as a build step in a mult-stage build https://hub.docker.com/r/healthsoft/audiowaveform-alpine.

**Comment by shealan** [comment]
@william00179 thanks for the quick reply. Yes, that's exactly what I am trying to do.

I am using a multistep Dockerfile where I need to somehow build the audiowaveform binary and place it into the /usr/local/bin directory of our docker environment for pushing to Lambda.

```
FROM genesix/docker-audiowaveform-alpine:latest AS audiowaveform-builder
FROM laravelphp/vapor:php74

RUN apk --update add --no-cache libmad libsndfile libid3tag gd boost boost-program_options zlib-static libpng-static boost-static
COPY --from=audiowaveform-builder /bin/audiowaveform /usr/local/bin

COPY . /var/task
```

This doesn't work, it the binary builds but the errors thrown makes me believe that built binary is not static as it seems to be missing things. For example:

```
symbol not found\nError relocating /usr/local/bin/audiowaveform: _ZN5boost15program_options3argB5cxx11E: symbol not found
```

**Comment by shealan** [comment]
Oh wow, please ignore me. I realised that your image works exactly the same way. Just replaced it and working perfectly. Thank you :)

**Pull request merged**
