### PR TITLE
Add build instructions for Arch Linux

### PR DESCRIPTION
**Pull request by pR0Ps**
I added this program to the [AUR](https://aur.archlinux.org/) to make it easy to install/update for Arch Linux users. This commit just adds a link to the AUR package in the README.

Note that the AUR is not a binary distribution platform, the package there is effectively just a build script that grabs the source from this repo, builds, and installs it.

I'm happy to transfer ownership of the package to a member of this team if required.

### CODE REVIEW

**Comment by chrisn** [comment]
Thanks, this is a great contribution! I have a couple of comments though:

* I'd prefer to base the releases on the tags in GitHub, rather than the current state of the master branch. Although master is generally stable, the HEAD doesn't always correspond to an official release, so may contain work in progress. What do you think?
* There's no need to transfer ownership, but I'd be happy to take it on if you prefer.

**Comment by pR0Ps** [comment]
The `-git` suffix in the AUR typically means the latest, possibly unstable version. Looking back, I probably should've just created an `audiowaveform` package instead since you tag releases pretty regularly. I'll create the `audiowaveform` package now and update the PR to link to it.

**Comment by pR0Ps** [comment]
I've made a new package `audiowaveform` that builds the latest release and updated the README.md to point to it.

**Comment by chrisn** [comment]
Thank you so much!

**Pull request merged**
